export enum ActionType {
  USER_CONNECTION_STATE_CHANGED = 'USER_CONNECTION_STATE_CHANGED',
  USER_ACTIVITY_CHANGED = 'USER_ACTIVITY_CHANGED',
  PHONE_DISPLAY_UPDATE = 'PHONE_DISPLAY_UPDATE',
  PHONE_DISPLAY_UPDATE_WITH_FOCUS = 'PHONE_DISPLAY_UPDATE_WITH_FOCUS',
  PHONE_STATE_CHANGED = 'PHONE_STATE_CHANGED',
  PHONE_INCOMING_CALL = 'PHONE_INCOMING_CALL',
  PHONE_OUTGOING_CALL = 'PHONE_OUTGOING_CALL',
  PHONE_CALL_UPDATE = 'PHONE_CALL_UPDATE',
  PHONE_TOKEN_UPDATED = 'PHONE_TOKEN_UPDATED',
  PHONE_CONFIGURATION_UPDATED = 'PHONE_CONFIGURATION_UPDATED',
  PHONE_INPUT_DEVICE_UPDATED = 'PHONE_INPUT_DEVICE_UPDATED',
  PHONE_OUTPUT_DEVICE_UPDATED = 'PHONE_OUTPUT_DEVICE_UPDATED',
  PHONE_INPUT_DEVICE_LOST = 'PHONE_INPUT_DEVICE_LOST',
  PHONE_OUTPUT_DEVICE_LOST = 'PHONE_OUTPUT_DEVICE_LOST',
  WORKSPACE_VIEW = 'WORKSPACE_VIEW',
  WORKSPACE_NOTIFICATION_SHOW = 'WORKSPACE_NOTIFICATION_SHOW',
  WORKSPACE_NOTIFICATION_HIDE = 'WORKSPACE_NOTIFICATION_HIDE',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CONFIGURATION_CHANGED = 'USER_CONFIGURATION_CHANGED',
}

export interface Action {
  type: ActionType;
  payload: any;
}
