export enum ActionType {
  USER_CONNECTION_STATE_CHANGED = 'USER_CONNECTION_STATE_CHANGED',
  USER_ACTIVITY_CHANGED = 'USER_ACTIVITY_CHANGED',
  PHONE_DISPLAY_UPDATE = 'PHONE_DISPLAY_UPDATE',
  PHONE_DISPLAY_UPDATE_WITH_FOCUS = 'PHONE_DISPLAY_UPDATE_WITH_FOCUS',
  PHONE_STATE_CHANGED = 'PHONE_STATE_CHANGED',
  PHONE_INCOMING_CALL = 'PHONE_INCOMING_CALL',
  PHONE_OUTGOING_CALL = 'PHONE_OUTGOING_CALL',
  PHONE_TOKEN_UPDATED = 'PHONE_TOKEN_UPDATED',
  PHONE_CONFIGURATION_UPDATED = 'PHONE_CONFIGURATION_UPDATED',
  WORKSPACE_VIEW = 'WORKSPACE_VIEW',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CONFIGURATION_CHANGED = 'USER_CONFIGURATION_CHANGED',
}

export interface Action {
  type: ActionType;
  payload: any;
}
